; PlatformIO Project Configuration File
;
;  Build options: build flags, source filter
;  Upload options: custom upload port, speed and extra flags
;  Library options: dependencies, extra library storages
;  Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
build_flags = 
	-D APP_VERSION=0.0.1

[env:esp32-c6-touch-amoled-206]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.partitions = app3M_fat9M_16MB.csv
lib_deps = 
	lvgl/lvgl@^9.5.0
	moononournation/GFX Library for Arduino@^1.6.7
	lewisxhe/SensorLib@^0.4.1
	lewisxhe/XPowersLib@^0.3.3
	h2zero/NimBLE-Arduino@^2.5.1
build_flags = 
	${env.build_flags}
	-I include
	-D LV_CONF_INCLUDE_SIMPLE=1
	-D USER_SETUP_LOADED=1
	-D BOARD_HAS_PSRAM=0
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
